/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.componets.bodypages;

import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.JTextPane;
import view.componets.ListConstructor;
import view.componets.Theme;

/**
 *
 * @author johnrojas
 */
public class AccidentDetails extends javax.swing.JFrame {
    /**
     * Creates new form NewReportVehicleList
     */
    public AccidentDetails() {
        setUndecorated(true);
        setAlwaysOnTop(true);
        initComponents();
        setVisible(false);
    }

    public JLabel getAccidentDate() {
        return AccidentDate;
    }

    public JLabel getAccidentId() {
        return AccidentId;
    }

    public JLabel getAccidentLocation() {
        return AccidentLocation;
    }

    public JLabel getCmdClose() {
        return cmdClose;
    }

    public JTextPane getAccidentComments() {
        return AccidentComments;
    }

    public ListConstructor getListPanel() {
        return listPanel;
    }

    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        AccidentId = new javax.swing.JLabel();
        cmdClose = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labelLocation = new javax.swing.JLabel();
        AccidentLocation = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        AccidentDate = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        scrollAccidentComments = new javax.swing.JScrollPane();
        AccidentComments = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        HeaderTable = new javax.swing.JPanel();
        TH_plate = new javax.swing.JLabel();
        TH_model = new javax.swing.JLabel();
        TH_year = new javax.swing.JLabel();
        TH_owner = new javax.swing.JLabel();
        TH_address = new javax.swing.JLabel();
        TH_phone = new javax.swing.JLabel();
        listPanel = new view.componets.ListConstructor();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(Theme.Color.BG);

        Header.setBackground(Theme.Color.DARK);

        Title.setBackground(Theme.Color.DARK);
        Title.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        Title.setForeground(Theme.Color.OLIVE);
        Title.setText("Accident Report #");

        AccidentId.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        AccidentId.setForeground(Theme.Color.OLIVE);
        AccidentId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AccidentId.setText("0");

        cmdClose.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        cmdClose.setForeground(Theme.Color.OLIVE);
        cmdClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cmdClose.setText("X");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AccidentId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmdClose, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AccidentId, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(Title, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmdClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBackground(Theme.getColor(Theme.BLACK,150));

        labelLocation.setForeground(Theme.Color.OLIVE);
        labelLocation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLocation.setText("Location:");

        AccidentLocation.setForeground(Theme.getColor(Theme.CLOUD));
        AccidentLocation.setText("...");

        dateLabel.setForeground(Theme.Color.OLIVE);
        dateLabel.setText("Date");

        AccidentDate.setForeground(Theme.getColor(Theme.CLOUD));
        AccidentDate.setText("...");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AccidentLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(AccidentDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelLocation, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(dateLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AccidentLocation, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AccidentDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.setBackground(null);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setForeground(Theme.Color.OLIVE);
        jLabel1.setText("Comments");

        scrollAccidentComments.setBackground(Theme.getColor(Theme.DARK_GRAY,50));
        scrollAccidentComments.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, Theme.getColor(Theme.DARK_GRAY)), javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, Theme.getColor(Theme.DEEP_DARK,100))));

        AccidentComments.setEditable(false);
        AccidentComments.setBackground(Theme.getColor(Theme.DARK_GRAY,50));
        AccidentComments.setBorder(null);
        AccidentComments.setContentType("text/html"); // NOI18N
        AccidentComments.setForeground(Theme.Color.OLIVE);
        AccidentComments.setText("");
        AccidentComments.setMargin(new java.awt.Insets(10, 10, 10, 10));
        scrollAccidentComments.setViewportView(AccidentComments);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollAccidentComments)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 888, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollAccidentComments, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel2.setForeground(Theme.getColor(Theme.CLOUD));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Vehicles Involved");

        HeaderTable.setBackground(Theme.Color.DARK);
        HeaderTable.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, Theme.Color.OLIVE));
        HeaderTable.setForeground(Theme.Color.OLIVE);
        HeaderTable.setLayout(new java.awt.GridLayout(1, 5));

        TH_plate.setForeground(Theme.Color.OLIVE);
        TH_plate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TH_plate.setText("PLATE");
        HeaderTable.add(TH_plate);

        TH_model.setForeground(Theme.Color.OLIVE);
        TH_model.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TH_model.setText("MODEL");
        HeaderTable.add(TH_model);

        TH_year.setForeground(Theme.Color.OLIVE);
        TH_year.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TH_year.setText("YEAR");
        HeaderTable.add(TH_year);

        TH_owner.setForeground(Theme.Color.OLIVE);
        TH_owner.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TH_owner.setText("OWNER");
        HeaderTable.add(TH_owner);

        TH_address.setForeground(Theme.Color.OLIVE);
        TH_address.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TH_address.setText("OWNER ADDRESS");
        HeaderTable.add(TH_address);

        TH_phone.setForeground(Theme.Color.OLIVE);
        TH_phone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TH_phone.setText("OWNER PHONE");
        HeaderTable.add(TH_phone);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(HeaderTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(HeaderTable, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(listPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane AccidentComments;
    private javax.swing.JLabel AccidentDate;
    private javax.swing.JLabel AccidentId;
    private javax.swing.JLabel AccidentLocation;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel HeaderTable;
    private javax.swing.JLabel TH_address;
    private javax.swing.JLabel TH_model;
    private javax.swing.JLabel TH_owner;
    private javax.swing.JLabel TH_phone;
    private javax.swing.JLabel TH_plate;
    private javax.swing.JLabel TH_year;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel cmdClose;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelLocation;
    private view.componets.ListConstructor listPanel;
    private javax.swing.JScrollPane scrollAccidentComments;
    // End of variables declaration//GEN-END:variables
}
