/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.componets.bodypages;

import javax.swing.JLabel;
import javax.swing.JTextField;
import view.componets.Button;
import view.componets.Theme;

/**
 *
 * @author johnrojas
 */
public class AddVehicleBody extends javax.swing.JPanel {

    /**
     * Creates new form AddVechicleBody
     */
    public AddVehicleBody() {
        initComponents();
    }

    public JLabel getError() {
        return error;
    }

    public JTextField getModelInput() {
        return modelInput;
    }

    public JTextField getOwnerNameInput() {
        return ownerNameInput;
    }

    public JTextField getOwnerPhoneInput() {
        return ownerPhoneInput;
    }

    public JTextField getOwnerAddressInput() {
        return ownerAddressInput;
    }
    
    public JTextField getPlateInput() {
        return plateInput;
    }

    public Button getSubmit() {
        return submit;
    }

    public JTextField getYearInput() {
        return yearInput;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rowPlate = new javax.swing.JPanel();
        plateLabel = new javax.swing.JLabel();
        plateInput = new javax.swing.JTextField();
        rowModel = new javax.swing.JPanel();
        modelLabel = new javax.swing.JLabel();
        modelInput = new javax.swing.JTextField();
        rowYear = new javax.swing.JPanel();
        yearLabel = new javax.swing.JLabel();
        yearInput = new javax.swing.JTextField();
        divider = new javax.swing.JPanel();
        rowOwnerName = new javax.swing.JPanel();
        ownerNameLabel = new javax.swing.JLabel();
        ownerNameInput = new javax.swing.JTextField();
        rowOwnerAddress = new javax.swing.JPanel();
        ownerAddressLabel = new javax.swing.JLabel();
        ownerAddressInput = new javax.swing.JTextField();
        rowOwnerPhone = new javax.swing.JPanel();
        ownerPhoneLabel = new javax.swing.JLabel();
        ownerPhoneInput = new javax.swing.JTextField();
        rowSubmit = new javax.swing.JPanel();
        error = new javax.swing.JLabel();
        submit = new view.componets.Button();

        setBackground(null);
        setPreferredSize(new java.awt.Dimension(900, 700));

        rowPlate.setBackground(null);
        rowPlate.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, Theme.Color.CLEAR_10));
        rowPlate.setForeground(Theme.Color.CLEAR_20);
        rowPlate.setLayout(new java.awt.GridLayout(1, 2));

        plateLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        plateLabel.setForeground(Theme.Color.OLIVE);
        plateLabel.setText("Plate Number");
        plateLabel.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createMatteBorder(0, 10, 0, 10, Theme.Color.TRANSPARENT)));
        plateLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        rowPlate.add(plateLabel);

        plateInput.setBackground(Theme.Color.CLEAR_10);
        plateInput.setForeground(Theme.Color.CLEAR);
        plateInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        plateInput.setToolTipText("");
        plateInput.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(7, 0, 7, 0, Theme.Color.BG), null));
        plateInput.setCaretColor(Theme.Color.CLEAR);
        plateInput.setMargin(new java.awt.Insets(10, 0, 10, 0));
        rowPlate.add(plateInput);

        rowModel.setBackground(null);
        rowModel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, Theme.Color.CLEAR_10));
        rowModel.setForeground(Theme.Color.CLEAR_20);
        rowModel.setLayout(new java.awt.GridLayout(1, 2));

        modelLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        modelLabel.setForeground(Theme.Color.OLIVE);
        modelLabel.setText("Model");
        modelLabel.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createMatteBorder(0, 10, 0, 10, Theme.Color.TRANSPARENT)));
        modelLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        rowModel.add(modelLabel);

        modelInput.setBackground(Theme.Color.CLEAR_10);
        modelInput.setForeground(Theme.Color.CLEAR);
        modelInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        modelInput.setToolTipText("");
        modelInput.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(7, 0, 7, 0, Theme.Color.BG), null));
        modelInput.setCaretColor(Theme.Color.CLEAR);
        modelInput.setMargin(new java.awt.Insets(10, 0, 10, 0));
        rowModel.add(modelInput);

        rowYear.setBackground(null);
        rowYear.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, Theme.Color.CLEAR_10));
        rowYear.setForeground(Theme.Color.CLEAR_20);
        rowYear.setLayout(new java.awt.GridLayout(1, 2));

        yearLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        yearLabel.setForeground(Theme.Color.OLIVE);
        yearLabel.setText("Year");
        yearLabel.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createMatteBorder(0, 10, 0, 10, Theme.Color.TRANSPARENT)));
        yearLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        rowYear.add(yearLabel);

        yearInput.setBackground(Theme.Color.CLEAR_10);
        yearInput.setForeground(Theme.Color.CLEAR);
        yearInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        yearInput.setToolTipText("");
        yearInput.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(7, 0, 7, 0, Theme.Color.BG), null));
        yearInput.setCaretColor(Theme.Color.CLEAR);
        yearInput.setMargin(new java.awt.Insets(10, 0, 10, 0));
        rowYear.add(yearInput);

        divider.setBackground(Theme.Color.CLEAR_20);
        divider.setForeground(Theme.Color.CLEAR_20);

        rowOwnerName.setBackground(null);
        rowOwnerName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, Theme.Color.CLEAR_10));
        rowOwnerName.setForeground(Theme.Color.CLEAR_20);
        rowOwnerName.setLayout(new java.awt.GridLayout(1, 2));

        ownerNameLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        ownerNameLabel.setForeground(Theme.Color.OLIVE);
        ownerNameLabel.setText("Owner Name");
        ownerNameLabel.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createMatteBorder(0, 10, 0, 10, Theme.Color.TRANSPARENT)));
        ownerNameLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        rowOwnerName.add(ownerNameLabel);

        ownerNameInput.setBackground(Theme.Color.CLEAR_10);
        ownerNameInput.setForeground(Theme.Color.CLEAR);
        ownerNameInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ownerNameInput.setToolTipText("");
        ownerNameInput.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(7, 0, 7, 0, Theme.Color.BG), null));
        ownerNameInput.setCaretColor(Theme.Color.CLEAR);
        ownerNameInput.setMargin(new java.awt.Insets(10, 0, 10, 0));
        rowOwnerName.add(ownerNameInput);

        rowOwnerAddress.setBackground(null);
        rowOwnerAddress.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, Theme.Color.CLEAR_10));
        rowOwnerAddress.setForeground(Theme.Color.CLEAR_20);
        rowOwnerAddress.setLayout(new java.awt.GridLayout(1, 2));

        ownerAddressLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        ownerAddressLabel.setForeground(Theme.Color.OLIVE);
        ownerAddressLabel.setText("Owner Address");
        ownerAddressLabel.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createMatteBorder(0, 10, 0, 10, Theme.Color.TRANSPARENT)));
        ownerAddressLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        rowOwnerAddress.add(ownerAddressLabel);

        ownerAddressInput.setBackground(Theme.Color.CLEAR_10);
        ownerAddressInput.setForeground(Theme.Color.CLEAR);
        ownerAddressInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ownerAddressInput.setToolTipText("");
        ownerAddressInput.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(7, 0, 7, 0, Theme.Color.BG), null));
        ownerAddressInput.setCaretColor(Theme.Color.CLEAR);
        ownerAddressInput.setMargin(new java.awt.Insets(10, 0, 10, 0));
        rowOwnerAddress.add(ownerAddressInput);

        rowOwnerPhone.setBackground(null);
        rowOwnerPhone.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, Theme.Color.CLEAR_10));
        rowOwnerPhone.setForeground(Theme.Color.CLEAR_20);
        rowOwnerPhone.setLayout(new java.awt.GridLayout(1, 2));

        ownerPhoneLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        ownerPhoneLabel.setForeground(Theme.Color.OLIVE);
        ownerPhoneLabel.setText("Owner Phone Number");
        ownerPhoneLabel.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createMatteBorder(0, 10, 0, 10, Theme.Color.TRANSPARENT)));
        ownerPhoneLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        rowOwnerPhone.add(ownerPhoneLabel);

        ownerPhoneInput.setBackground(Theme.Color.CLEAR_10);
        ownerPhoneInput.setForeground(Theme.Color.CLEAR);
        ownerPhoneInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ownerPhoneInput.setToolTipText("");
        ownerPhoneInput.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(7, 0, 7, 0, Theme.Color.BG), null));
        ownerPhoneInput.setCaretColor(Theme.Color.CLEAR);
        ownerPhoneInput.setMargin(new java.awt.Insets(10, 0, 10, 0));
        rowOwnerPhone.add(ownerPhoneInput);

        rowSubmit.setBackground(null);
        rowSubmit.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, Theme.Color.CLEAR_10));
        rowSubmit.setForeground(Theme.Color.CLEAR_20);
        rowSubmit.setLayout(new java.awt.GridLayout(1, 2));

        error.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        error.setForeground(Theme.Color.DANGER);
        error.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createMatteBorder(0, 10, 0, 10, Theme.Color.TRANSPARENT)));
        error.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        rowSubmit.add(error);

        submit.setText("submit");
        rowSubmit.add(submit);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rowPlate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rowModel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rowYear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(divider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rowOwnerName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rowOwnerAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rowOwnerPhone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rowSubmit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(250, 250, 250))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(rowPlate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rowModel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rowYear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(divider, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rowOwnerName, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rowOwnerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rowOwnerPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rowSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(158, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel divider;
    private javax.swing.JLabel error;
    private javax.swing.JTextField modelInput;
    private javax.swing.JLabel modelLabel;
    private javax.swing.JTextField ownerAddressInput;
    private javax.swing.JLabel ownerAddressLabel;
    private javax.swing.JTextField ownerNameInput;
    private javax.swing.JLabel ownerNameLabel;
    private javax.swing.JTextField ownerPhoneInput;
    private javax.swing.JLabel ownerPhoneLabel;
    private javax.swing.JTextField plateInput;
    private javax.swing.JLabel plateLabel;
    private javax.swing.JPanel rowModel;
    private javax.swing.JPanel rowOwnerAddress;
    private javax.swing.JPanel rowOwnerName;
    private javax.swing.JPanel rowOwnerPhone;
    private javax.swing.JPanel rowPlate;
    private javax.swing.JPanel rowSubmit;
    private javax.swing.JPanel rowYear;
    private view.componets.Button submit;
    private javax.swing.JTextField yearInput;
    private javax.swing.JLabel yearLabel;
    // End of variables declaration//GEN-END:variables
}
