/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.componets.bodypages;

import view.PageAbstract;
import view.componets.Theme;
import java.awt.Dimension;
import javax.swing.JLabel;

/**
 *
 * @author johnrojas
 */
public class HomeBody extends javax.swing.JPanel {

    /**
     * Creates new form HomeBody
     */
    public HomeBody() {
        initComponents();
        config();
    }
    
    private void config(){
        //int bodyH = PageAbstract.PAGE_HEIGTH - PageAbstract.HEADER_HEIGTH;
        //setPreferredSize(new Dimension(PageAbstract.PAGE_WIDTH,bodyH));
    }
    
    public JLabel getTotalAccidentsLabel(){
        return this.totalAccidents;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcome = new javax.swing.JLabel();
        titleA = new javax.swing.JLabel();
        titleB = new javax.swing.JLabel();
        footer = new javax.swing.JLabel();
        totalAccidents = new javax.swing.JLabel();

        setBackground(Theme.Color.BG);

        welcome.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        welcome.setForeground(Theme.Color.CLEAR);
        welcome.setText("Wellcome to");

        titleA.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        titleA.setForeground(Theme.Color.OLIVE);
        titleA.setText("Traffic Accident Reporting");

        titleB.setForeground(Theme.Color.OLIVE);
        titleB.setText("Developed by: John Rojas - 12072801 | Powered By: CQUniversity");

        footer.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        footer.setForeground(Theme.Color.OLIVE);
        footer.setText("System (TARS) ");

        totalAccidents.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        totalAccidents.setForeground(Theme.Color.GRAY);
        totalAccidents.setText("...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titleB)
                .addGap(52, 52, 52))
            .addGroup(layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(welcome)
                    .addComponent(titleA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(footer)
                    .addComponent(totalAccidents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(367, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(231, 231, 231)
                .addComponent(welcome)
                .addGap(18, 18, 18)
                .addComponent(titleA, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(footer, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(totalAccidents)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addComponent(titleB)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel footer;
    private javax.swing.JLabel titleA;
    private javax.swing.JLabel titleB;
    private javax.swing.JLabel totalAccidents;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
