/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.componets.bodypages;

import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import view.componets.Button;
import view.componets.ListConstructor;
import view.componets.Selector;
import view.componets.Theme;

/**
 *
 * @author johnrojas
 */
public class NewReportBody extends javax.swing.JPanel {

    /**
     * Creates new form HomeBody
     */
    public NewReportBody() {
        initComponents();
    }

    public JTextField getLocationIN() {
        return locationIN;
    }

    public JTextArea getCommentsIN() {
        return commentsIN;
    }

    public Button getCmdVehiclesList() {
        return cmdVehiclesList;
    }

    public JLabel getInvolvedCars() {
        return involvedCars;
    }
    
    public Button getSubmit() {
        return submit;
    }

    public ListConstructor getListPanel() {
        return listPanel;
    }

    public JLabel getErrorLabel() {
        return errorLabel;
    }

    public JLabel getDateLabel() {
        return dateLabel;
    }

    public Selector getDayIN() {
        return dayIN;
    }

    public Selector getMonthIN() {
        return monthIN;
    }

    public Selector getYearIN() {
        return yearIN;
    }
    
    

    public Selector getHoursIN() {
        return hoursIN;
    }

    public Selector getMinutesIN() {
        return minutesIN;
    }

    public Selector getAmpmIN() {
        return ampmIN;
    }

   

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rowLocation = new javax.swing.JPanel();
        commentsLabel = new javax.swing.JLabel();
        locationLabel = new javax.swing.JLabel();
        locationIN = new javax.swing.JTextField();
        rowComments = new javax.swing.JPanel();
        comments = new javax.swing.JScrollPane();
        commentsIN = new javax.swing.JTextArea();
        rowInvolded = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        involvedCars = new javax.swing.JLabel();
        datetimePanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        ampmIN = new view.componets.Selector();
        minutesIN = new view.componets.Selector();
        hoursIN = new view.componets.Selector();
        yearIN = new view.componets.Selector();
        monthIN = new view.componets.Selector();
        dayIN = new view.componets.Selector();
        tHeader = new javax.swing.JPanel();
        th_plate = new javax.swing.JLabel();
        th_model = new javax.swing.JLabel();
        th_year = new javax.swing.JLabel();
        th_owner_name = new javax.swing.JLabel();
        th_owner_address = new javax.swing.JLabel();
        th_owner_phone = new javax.swing.JLabel();
        listPanel = new view.componets.ListConstructor();
        submit = new view.componets.Button();
        errorLabel = new javax.swing.JLabel();
        cmdVehiclesList = new view.componets.Button();

        setBackground(Theme.Color.BG);

        rowLocation.setBackground(null);

        commentsLabel.setForeground(Theme.Color.CLEAR);
        commentsLabel.setText("comments");
        commentsLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        locationLabel.setForeground(Theme.Color.CLEAR);
        locationLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        locationLabel.setText("Location");

        locationIN.setBackground(Theme.Color.TRANSPARENT);
        locationIN.setForeground(Theme.Color.OLIVE);
        locationIN.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        locationIN.setToolTipText("Where the accident happened");
        locationIN.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, Theme.Color.CLEAR_20));
        locationIN.setCaretColor(Theme.Color.OLIVE);
        locationIN.setMaximumSize(new java.awt.Dimension(200, 2147483647));

        javax.swing.GroupLayout rowLocationLayout = new javax.swing.GroupLayout(rowLocation);
        rowLocation.setLayout(rowLocationLayout);
        rowLocationLayout.setHorizontalGroup(
            rowLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rowLocationLayout.createSequentialGroup()
                .addComponent(commentsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(locationLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(locationIN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        rowLocationLayout.setVerticalGroup(
            rowLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(commentsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(locationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(locationIN, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        rowComments.setBackground(null);

        comments.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, Theme.Color.CLEAR_20));

        commentsIN.setBackground(Theme.Color.BG);
        commentsIN.setColumns(20);
        commentsIN.setForeground(Theme.Color.OLIVE);
        commentsIN.setRows(5);
        commentsIN.setToolTipText("Enter Accident Details");
        commentsIN.setWrapStyleWord(true);
        commentsIN.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, Theme.Color.TRANSPARENT)));
        commentsIN.setCaretColor(Theme.Color.OLIVE);
        comments.setViewportView(commentsIN);

        javax.swing.GroupLayout rowCommentsLayout = new javax.swing.GroupLayout(rowComments);
        rowComments.setLayout(rowCommentsLayout);
        rowCommentsLayout.setHorizontalGroup(
            rowCommentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(comments)
        );
        rowCommentsLayout.setVerticalGroup(
            rowCommentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rowCommentsLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(comments, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        rowInvolded.setBackground(Theme.Color.DARK);

        jLabel1.setForeground(Theme.Color.CLEAR);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Involved Vehicles");

        involvedCars.setForeground(Theme.Color.OLIVE);
        involvedCars.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        involvedCars.setText("0");

        datetimePanel.setBackground(null);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel3.setForeground(Theme.Color.CLEAR);
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("DATE");

        dateLabel.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        dateLabel.setForeground(Theme.Color.CLEAR);
        dateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dateLabel.setText("TIME");

        javax.swing.GroupLayout datetimePanelLayout = new javax.swing.GroupLayout(datetimePanel);
        datetimePanel.setLayout(datetimePanelLayout);
        datetimePanelLayout.setHorizontalGroup(
            datetimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datetimePanelLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dayIN, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(monthIN, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(yearIN, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hoursIN, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(minutesIN, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ampmIN, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        datetimePanelLayout.setVerticalGroup(
            datetimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datetimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ampmIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(minutesIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(hoursIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(yearIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(monthIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(dayIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout rowInvoldedLayout = new javax.swing.GroupLayout(rowInvolded);
        rowInvolded.setLayout(rowInvoldedLayout);
        rowInvoldedLayout.setHorizontalGroup(
            rowInvoldedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rowInvoldedLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(involvedCars, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(datetimePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        rowInvoldedLayout.setVerticalGroup(
            rowInvoldedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rowInvoldedLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rowInvoldedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(involvedCars, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(rowInvoldedLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rowInvoldedLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(datetimePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        tHeader.setBackground(Theme.Color.DARK);
        tHeader.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, Theme.Color.OLIVE));
        tHeader.setLayout(new java.awt.GridLayout(1, 6, 5, 0));

        th_plate.setForeground(Theme.Color.OLIVE);
        th_plate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        th_plate.setText("PLATE");
        tHeader.add(th_plate);

        th_model.setForeground(Theme.Color.OLIVE);
        th_model.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        th_model.setText("MODEL");
        tHeader.add(th_model);

        th_year.setForeground(Theme.Color.OLIVE);
        th_year.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        th_year.setText("YEAR");
        tHeader.add(th_year);

        th_owner_name.setForeground(Theme.Color.OLIVE);
        th_owner_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        th_owner_name.setText("OWNER");
        tHeader.add(th_owner_name);

        th_owner_address.setForeground(Theme.Color.OLIVE);
        th_owner_address.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        th_owner_address.setText("ADDRESS");
        tHeader.add(th_owner_address);

        th_owner_phone.setForeground(Theme.Color.OLIVE);
        th_owner_phone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        th_owner_phone.setText("PHONE");
        tHeader.add(th_owner_phone);

        submit.setText("Create Report");
        submit.setOpaque(false);

        errorLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        errorLabel.setForeground(Theme.Color.DANGER);
        errorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        cmdVehiclesList.setText("Select Vehicles");
        cmdVehiclesList.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        cmdVehiclesList.setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rowLocation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rowComments, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cmdVehiclesList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(errorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rowInvolded, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rowLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rowComments, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rowInvolded, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(listPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cmdVehiclesList, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(errorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.componets.Selector ampmIN;
    private view.componets.Button cmdVehiclesList;
    private javax.swing.JScrollPane comments;
    private javax.swing.JTextArea commentsIN;
    private javax.swing.JLabel commentsLabel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JPanel datetimePanel;
    private view.componets.Selector dayIN;
    private javax.swing.JLabel errorLabel;
    private view.componets.Selector hoursIN;
    private javax.swing.JLabel involvedCars;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private view.componets.ListConstructor listPanel;
    private javax.swing.JTextField locationIN;
    private javax.swing.JLabel locationLabel;
    private view.componets.Selector minutesIN;
    private view.componets.Selector monthIN;
    private javax.swing.JPanel rowComments;
    private javax.swing.JPanel rowInvolded;
    private javax.swing.JPanel rowLocation;
    private view.componets.Button submit;
    private javax.swing.JPanel tHeader;
    private javax.swing.JLabel th_model;
    private javax.swing.JLabel th_owner_address;
    private javax.swing.JLabel th_owner_name;
    private javax.swing.JLabel th_owner_phone;
    private javax.swing.JLabel th_plate;
    private javax.swing.JLabel th_year;
    private view.componets.Selector yearIN;
    // End of variables declaration//GEN-END:variables
}
