/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.componets.bodypages;

import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JTextField;
import view.componets.Button;
import view.componets.ListConstructor;
import view.componets.Theme;

/**
 *
 * @author johnrojas
 */
public class VehicleListBody extends javax.swing.JPanel {

    /**
     * Creates new form VehicleList
     */
    public VehicleListBody() {
        initComponents();
    }
    
    
    public JLabel getGuideLabel(){
        return Guide;
    }

    public JLabel getAddCmd() {
        return addCmd;
    }

    public JLabel getDeleteCmd() {
        return deleteCmd;
    }

    public JLabel getEditCmd() {
        return editCmd;
    }


    public JLabel getCurrentVehicleName() {
        return currentVehicleName;
    }

    public JLabel getCurrentVehiclePlate() {
        return currentVehiclePlate;
    }

    public ListConstructor getListPanel() {
        return listPanel;
    }

    public void setListPanel(ListConstructor listPanel) {
        this.listPanel = listPanel;
    }

    public JCheckBox getCheckOwner() {
        return checkOwner;
    }

    public JCheckBox getCheckPlate() {
        return checkPlate;
    }

    public Button getCmdClearFilter() {
        return cmdClearFilter;
    }

    public JTextField getFilterInput() {
        return filterInput;
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Guide = new javax.swing.JLabel();
        filterPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        checkPlate = new javax.swing.JCheckBox();
        checkOwner = new javax.swing.JCheckBox();
        filterInput = new javax.swing.JTextField();
        cmdClearFilter = new view.componets.Button();
        controls = new javax.swing.JPanel();
        addCmd = new javax.swing.JLabel();
        currentVehicleName = new javax.swing.JLabel();
        currentVehiclePlate = new javax.swing.JLabel();
        editCmd = new javax.swing.JLabel();
        deleteCmd = new javax.swing.JLabel();
        THead = new javax.swing.JPanel();
        TH_id = new javax.swing.JLabel();
        TH_model = new javax.swing.JLabel();
        TH_year = new javax.swing.JLabel();
        TH_numAccidents = new javax.swing.JLabel();
        TH_ownerName = new javax.swing.JLabel();
        TH_ownerAddress = new javax.swing.JLabel();
        TH_ownerPhone = new javax.swing.JLabel();
        listPanel = new view.componets.ListConstructor();

        Guide.setForeground(Theme.Color.CLEAR);
        Guide.setText("All Registered vehicles");
        Guide.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, Theme.Color.DARK));

        filterPanel.setBackground(null);
        java.awt.GridBagLayout filterPanelLayout = new java.awt.GridBagLayout();
        filterPanelLayout.rowHeights = new int[] {50};
        filterPanelLayout.columnWeights = new double[] {0.1, 100.0, 1.0};
        filterPanelLayout.rowWeights = new double[] {1.0};
        filterPanel.setLayout(filterPanelLayout);

        jPanel1.setBackground(null);
        jPanel1.setLayout(new java.awt.GridLayout(1, 3));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jLabel1.setForeground(Theme.Color.GRAY);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FILTER BY");
        jPanel1.add(jLabel1);

        checkPlate.setForeground(Theme.Color.GRAY);
        checkPlate.setText("plate");
        jPanel1.add(checkPlate);

        checkOwner.setForeground(Theme.Color.GRAY);
        checkOwner.setText("owner name");
        jPanel1.add(checkOwner);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        filterPanel.add(jPanel1, gridBagConstraints);

        filterInput.setBackground(Theme.Color.BG);
        filterInput.setForeground(Theme.Color.OLIVE);
        filterInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        filterInput.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, Theme.Color.OLIVE));
        filterInput.setCaretColor(Theme.Color.OLIVE);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        filterPanel.add(filterInput, gridBagConstraints);

        cmdClearFilter.setText("CLEAR FILTER");
        cmdClearFilter.setFont(new java.awt.Font("Lucida Grande", 0, 8)); // NOI18N
        cmdClearFilter.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 25);
        filterPanel.add(cmdClearFilter, gridBagConstraints);

        controls.setBackground(Theme.Color.DARK);
        controls.setPreferredSize(new java.awt.Dimension(0, 40));
        controls.setLayout(new java.awt.GridLayout(1, 5, 5, 0));

        addCmd.setBackground(Theme.Color.DARK);
        addCmd.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        addCmd.setForeground(Theme.Color.OLIVE);
        addCmd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addCmd.setText("NEW VEHICLE");
        addCmd.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(102, 102, 102)));
        addCmd.setOpaque(true);
        controls.add(addCmd);

        currentVehicleName.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        currentVehicleName.setForeground(Theme.getColor(Theme.CLOUD));
        currentVehicleName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        currentVehicleName.setText("No Selected");
        controls.add(currentVehicleName);

        currentVehiclePlate.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        currentVehiclePlate.setForeground(Theme.getColor(Theme.CLOUD));
        currentVehiclePlate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        currentVehiclePlate.setText("-");
        controls.add(currentVehiclePlate);

        editCmd.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        editCmd.setForeground(Theme.getColor(Theme.CLOUD));
        editCmd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editCmd.setText("EDIT");
        controls.add(editCmd);

        deleteCmd.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        deleteCmd.setForeground(Theme.getColor(Theme.CLOUD));
        deleteCmd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deleteCmd.setText("DELETE");
        controls.add(deleteCmd);

        THead.setBackground(Theme.Color.DARK);
        THead.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, Theme.Color.OLIVE));
        THead.setForeground(Theme.Color.CLEAR_20);
        THead.setPreferredSize(new java.awt.Dimension(0, 40));
        THead.setLayout(new java.awt.GridLayout(1, 7, 5, 0));

        TH_id.setForeground(Theme.Color.OLIVE);
        TH_id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TH_id.setText("PLATE #");
        THead.add(TH_id);

        TH_model.setForeground(Theme.Color.OLIVE);
        TH_model.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TH_model.setText("MODEL");
        THead.add(TH_model);

        TH_year.setForeground(Theme.Color.OLIVE);
        TH_year.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TH_year.setText("YEAR");
        THead.add(TH_year);

        TH_numAccidents.setForeground(Theme.Color.OLIVE);
        TH_numAccidents.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TH_numAccidents.setText("ACCIDENTS");
        THead.add(TH_numAccidents);

        TH_ownerName.setForeground(Theme.Color.OLIVE);
        TH_ownerName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TH_ownerName.setText("OWNER");
        THead.add(TH_ownerName);

        TH_ownerAddress.setForeground(Theme.Color.OLIVE);
        TH_ownerAddress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TH_ownerAddress.setText("ADDRESS");
        THead.add(TH_ownerAddress);

        TH_ownerPhone.setForeground(Theme.Color.OLIVE);
        TH_ownerPhone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TH_ownerPhone.setText("PHONE");
        THead.add(TH_ownerPhone);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Guide, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(filterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(controls, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(THead, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(listPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(filterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Guide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(controls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(THead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Guide;
    private javax.swing.JLabel TH_id;
    private javax.swing.JLabel TH_model;
    private javax.swing.JLabel TH_numAccidents;
    private javax.swing.JLabel TH_ownerAddress;
    private javax.swing.JLabel TH_ownerName;
    private javax.swing.JLabel TH_ownerPhone;
    private javax.swing.JLabel TH_year;
    private javax.swing.JPanel THead;
    private javax.swing.JLabel addCmd;
    private javax.swing.JCheckBox checkOwner;
    private javax.swing.JCheckBox checkPlate;
    private view.componets.Button cmdClearFilter;
    private javax.swing.JPanel controls;
    private javax.swing.JLabel currentVehicleName;
    private javax.swing.JLabel currentVehiclePlate;
    private javax.swing.JLabel deleteCmd;
    private javax.swing.JLabel editCmd;
    private javax.swing.JTextField filterInput;
    private javax.swing.JPanel filterPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private view.componets.ListConstructor listPanel;
    // End of variables declaration//GEN-END:variables
}
