/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.componets;

import presenter.PagesHandler;
import view.PageAbstract;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JPanel;


/**
 *
 * @author johnrojas
 */
public class Dashboard extends JPanel {
    public static int DEFAULT_WIDTH = 250;
    
    private ArrayList<DashboardItem> items;
    
    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        start();
    }
    
    private void start(){
        setBackground(Theme.Color.DARK);
        setPreferredSize(new Dimension(DEFAULT_WIDTH+5, PageAbstract.PAGE_HEIGTH));
        items = new ArrayList<>();
        //titles:
        homeItem.setTitle("Home");
        reportItem.setTitle("New Report");
        accidentItem.setTitle("Accident List");
        vehicleItem.setTitle("Vehicle List");
        
        
        homeItem.setPage(PagesHandler.PAGES.HOME);
        accidentItem.setPage(PagesHandler.PAGES.ACCITENS);
        reportItem.setPage(PagesHandler.PAGES.NEW_REPORT);
        vehicleItem.setPage(PagesHandler.PAGES.VEHICLES);
        
        homeItem.setItemIcon(Theme.ICON.HOME);
        reportItem.setItemIcon(Theme.ICON.REPORT);
        accidentItem.setItemIcon(Theme.ICON.ACCIDENT);
        vehicleItem.setItemIcon(Theme.ICON.VEHICLE);
        
        items.add(homeItem);
        items.add(reportItem);
        items.add(accidentItem);
        items.add(vehicleItem);
    }
    
    public ArrayList<DashboardItem> getItems(){
        return items;
    }
    
    public DashboardItem getItemByName(String name){
        for(DashboardItem match:items)
            if(match.getName().equals(name))return match;
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mBorder = new javax.swing.JPanel();
        container = new javax.swing.JPanel();
        homeItem = new view.componets.DashboardItem();
        reportItem = new view.componets.DashboardItem();
        accidentItem = new view.componets.DashboardItem();
        vehicleItem = new view.componets.DashboardItem();

        setBackground(Theme.Color.DARK);
        setPreferredSize(new java.awt.Dimension(255, 765));

        mBorder.setBackground(Theme.Color.OLIVE);

        javax.swing.GroupLayout mBorderLayout = new javax.swing.GroupLayout(mBorder);
        mBorder.setLayout(mBorderLayout);
        mBorderLayout.setHorizontalGroup(
            mBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        mBorderLayout.setVerticalGroup(
            mBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        container.setBackground(Theme.Color.DARK);
        container.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(homeItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accidentItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vehicleItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reportItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(homeItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(reportItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(accidentItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(vehicleItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(559, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(mBorder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mBorder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.componets.DashboardItem accidentItem;
    private javax.swing.JPanel container;
    private view.componets.DashboardItem homeItem;
    private javax.swing.JPanel mBorder;
    private view.componets.DashboardItem reportItem;
    private view.componets.DashboardItem vehicleItem;
    // End of variables declaration//GEN-END:variables
}
