/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.componets;

/**
 *
 * @author johnrojas
 */
public class RowAccident extends javax.swing.JPanel {

    /**
     * Creates new form RowAccident
     */
    public RowAccident() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        accident_id = new javax.swing.JLabel();
        location = new javax.swing.JLabel();
        description = new javax.swing.JLabel();
        vehicle_id = new javax.swing.JLabel();
        owner_id = new javax.swing.JLabel();

        setBackground(null);
        setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, Theme.Color.OLIVE));
        setPreferredSize(new java.awt.Dimension(950, 40));
        setLayout(new java.awt.GridLayout(1, 5, 5, 0));

        accident_id.setForeground(Theme.Color.CLEAR);
        accident_id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        accident_id.setText("1");
        accident_id.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        add(accident_id);

        location.setForeground(Theme.Color.CLEAR);
        location.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        location.setText("West Gate Bridge");
        location.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        add(location);

        description.setForeground(Theme.Color.CLEAR);
        description.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        description.setText("two cars crashed");
        description.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        add(description);

        vehicle_id.setForeground(Theme.Color.CLEAR);
        vehicle_id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vehicle_id.setText("1234 ABC | 567 DEF");
        vehicle_id.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        add(vehicle_id);

        owner_id.setForeground(Theme.Color.CLEAR);
        owner_id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        owner_id.setText("Tony Stark | Tomas Wayne");
        owner_id.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        add(owner_id);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accident_id;
    private javax.swing.JLabel description;
    private javax.swing.JLabel location;
    private javax.swing.JLabel owner_id;
    private javax.swing.JLabel vehicle_id;
    // End of variables declaration//GEN-END:variables
}
