/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import view.componets.Dashboard;
import view.componets.Theme;
import java.awt.Dimension;
import javax.swing.JPanel;

/**
 *
 * @author johnrojas
 */
public class GUIStructure extends javax.swing.JFrame {
    PageAbstract current;
    /**
     * Creates new form GUIStructure
     */
    public GUIStructure() {
        initComponents();
    }
    
    public void start(){
        setBackground(Theme.Color.DARK);
        setVisible(true);
        setLocationRelativeTo(null);
    }

    public Dashboard getNav() {
        return nav;
    }

    public JPanel getView() {
        return view;
    }

    public PageAbstract getCurrent() {
        return current;
    }

    public void setCurrent(PageAbstract current) {
        this.current = current;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nav = new view.componets.Dashboard();
        view = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(Theme.Color.OLIVE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));

        nav.setBackground(Theme.Color.DARK);

        view.setBackground(Theme.Color.BG);
        view.setPreferredSize(new Dimension(PageAbstract.PAGE_WIDTH,PageAbstract.PAGE_HEIGTH));
        view.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(nav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(view, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(view, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(nav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.componets.Dashboard nav;
    private javax.swing.JPanel view;
    // End of variables declaration//GEN-END:variables
}
