/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import presenter.PagesHandler.PAGES;
import view.componets.DashboardItem;
import view.componets.Theme;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import presenter.AppPresenter;
import presenter.Model;
import presenter.View;


/**
 *
 * @author johnrojas
 */
public abstract class PageAbstract extends javax.swing.JPanel {
    public static final int PAGE_WIDTH = 1116;//1366-dashboard_wirth
    public static final int PAGE_HEIGTH = 768;
    public static final int HEADER_HEIGTH = 55;
    
    
    private PAGES pageId;
    protected Model modelCtx;
    protected View viewCtx;
    
    protected abstract void initConfiguration();
    
    /**
     * Creates new form PageAbstract
     */
    public PageAbstract() {
        initComponents();
    }
    
    public void start(AppPresenter ctx){
        modelCtx = ctx.getModelPresenter();
        viewCtx = ctx.getViewPresenter();
        close.setVisible(false);
        initConfiguration();
    }

    protected void activeCloseBack(PAGES page){
        if(viewCtx == null)return;
        close.setVisible(true);
        MouseAdapter ma = new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                viewCtx.getPagesHandler().openPage(page);
            }
            
        };
        
        //close.addMouseListener(null);
        close.addMouseListener(ma);
    }
    
    public void disableDashItem(){
        if(viewCtx == null || pageId == null)return;
        disableDashItem(pageId);
    }
    
    protected void disableDashItem(PAGES name){
        DashboardItem item = viewCtx.getPagesHandler().getDashItemByPage(name);
        viewCtx.getPagesHandler().disableDashboardItem(item);
    }
    
    
    public JPanel getSection() {
        return section;
    }

    public PAGES getPageId() {
        return pageId;
    }

    public void setPageId(PAGES pageId) {
        this.pageId = pageId;
    }
    
    protected void setPageTitle(String title){
        pageTitle.setText(title);
    }
    
    protected void setPageIcon(String name){
        iconHeader.setIcon(Theme.ICON.getIcon(name));
    }

    public JScrollPane getBody() {
        return body;
    }
    
    public void appendBody(JPanel panel){
        body.setViewportView(panel);
        panel.setBackground(Theme.Color.BG);
    }
    
    
    public abstract void updateData();
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        section = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        iconHeader = new javax.swing.JLabel();
        pageTitle = new javax.swing.JLabel();
        close = new javax.swing.JButton();
        bodyContainer = new javax.swing.JPanel();
        body = new javax.swing.JScrollPane();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1000, 768));

        section.setBackground(new java.awt.Color(51, 51, 51));

        header.setBackground(Theme.Color.DARK);
        header.setPreferredSize(new Dimension(PAGE_WIDTH,HEADER_HEIGTH));

        iconHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        pageTitle.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        pageTitle.setForeground(Theme.Color.OLIVE);
        pageTitle.setText("title");
        pageTitle.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, Theme.Color.CLEAR_20));
        pageTitle.setPreferredSize(new java.awt.Dimension(15, 50));

        close.setBackground(null);
        close.setForeground(Theme.Color.OLIVE);
        close.setText("X");
        close.setBorder(null);
        close.setContentAreaFilled(false);
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        close.setPreferredSize(new java.awt.Dimension(50, 50));
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(iconHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pageTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconHeader, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pageTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(close, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        bodyContainer.setBackground(Theme.Color.BG);
        bodyContainer.setLayout(new java.awt.CardLayout());

        body.setBackground(new java.awt.Color(153, 153, 255));
        body.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        body.setOpaque(false);
        body.setPreferredSize(new java.awt.Dimension(990, 765));
        bodyContainer.add(body, "card2");

        javax.swing.GroupLayout sectionLayout = new javax.swing.GroupLayout(section);
        section.setLayout(sectionLayout);
        sectionLayout.setHorizontalGroup(
            sectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sectionLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(sectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
                    .addComponent(bodyContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        sectionLayout.setVerticalGroup(
            sectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sectionLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bodyContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(section, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(section, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_closeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane body;
    private javax.swing.JPanel bodyContainer;
    private javax.swing.JButton close;
    private javax.swing.JPanel header;
    private javax.swing.JLabel iconHeader;
    private javax.swing.JLabel pageTitle;
    private javax.swing.JPanel section;
    // End of variables declaration//GEN-END:variables
}
